import type { Metadata } from 'next';
import { Jost } from 'next/font/google';
import '@/styles/globals.scss';
import Header from '@/components/Header';

const jost = Jost({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Designo Multi Page Website | Home',
  description: 'Generated by create next app',
};

const RootLayout = ({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) => {
  return (
    <html lang='ja'>
      <body className={jost.className}>
        <Header />
        {children}
      </body>
    </html>
  );
};

export default RootLayout;
